### ISSUE TITLE
GraphQL vs REST vs both?

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/timdex#212]
As of now, we have a GraphQL implementation that implements much of the REST features.

We are also starting to discuss adding new features to TIMDEX!.

We should discuss and then decide if maintaining both GraphQL and REST is appropriate for this work and if so should they always be at feature parity.

Please add comments to this issue with any questions about the scope of this decision as well as thoughts on what decision we should make here.

**Comment by gravesm** [comment]
What level of work is involved to maintain both?

**Comment by JPrevost** [comment]
To maintain the current feature set, very little. However, as we consider additional features I think it could lead to potentially doubling of the work unless with have one endpoint effectively call the other.

For instance, if we treat the GraphQL endpoint as our primary development endpoint and start new features first in GraphQL, we could then treat the REST API as a client of the GraphQL endpoint rather than calling ElasticSearch directly. However, that makes me curious if the REST API should be a separate project if it's really just a wrapper or if would feel okay to leave them both as one app.

I think further discussion on this in context potentially with what our larger direction for APIs is going to be (outside of timdex). If our larger goal is to develop REST, we should stick with REST and maybe provide GraphQL as a best effort beta. If our larger goal is to develop GraphQL, we should consider deprecating the 1.0 REST API and transitioning over the next set of features to GraphQL only.
